"""
research_summary.py — the written daily research summary.

Reads the JSONs the pipeline just produced (tear sheets, risk engine, factors,
the pipeline run record) and renders a single dated markdown brief:
regime → strategy performance (incl. walk-forward + Monte Carlo) → risk → top
factor signals → pipeline status. Written to results/research_summary.md, which
the dashboard's Reports tab lists automatically.

RESEARCH ONLY — reads results/*.json, writes one markdown file; places no orders.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

RESULTS_DIR = Path(__file__).parent / "results"


def _load(name):
    fp = RESULTS_DIR / name
    if not fp.exists():
        return None
    try:
        return json.loads(fp.read_text())
    except ValueError:
        return None


def _pct(x, signed=False):
    if x is None:
        return "—"
    return f"{x*100:+.1f}%" if signed else f"{x*100:.1f}%"


def _num(x, fmt="{:.2f}"):
    return fmt.format(x) if x is not None else "—"


def _strategy_rows(strategies: dict) -> list[str]:
    rows = ["| Strategy | CAGR | Max DD | Sharpe | Walk-forward | "
            "Monte Carlo CAGR (p5–p95) | Regime |",
            "|---|---|---|---|---|---|---|"]
    for s in strategies.values():
        if s.get("kind") != "equity":
            continue
        f = s.get("full") or {}
        wf = s.get("walk_forward") or []
        pos = sum(1 for w in wf if (w.get("cagr") or 0) > 0)
        wf_txt = f"{pos}/{len(wf)} segments +" if wf else "—"
        mc = s.get("monte_carlo") or {}
        mc_txt = (f"{_pct(mc.get('cagr_p5'), True)} … {_pct(mc.get('cagr_p95'), True)}"
                  if mc else "—")
        fit = "in" if (s.get("regime_compat") or {}).get("compatible") else "out"
        rows.append(
            f"| {s.get('label', s.get('name'))} | {_pct(f.get('cagr'), True)} | "
            f"{_pct(f.get('max_drawdown'))} | {_num(f.get('sharpe'))} | "
            f"{wf_txt} | {mc_txt} | {fit} |")
    return rows


def build_summary() -> str:
    ts = _load("tearsheets.json") or {}
    risk = _load("risk_engine.json")
    factors = _load("factors.json")

    L = [f"# Daily Research Summary — {date.today().isoformat()}", "",
         "_Generated by `research_pipeline.py`. Paper / simulated research — "
         "no order-placement code exists. Pipeline health: see the Automation tab._", ""]

    rg = ts.get("regime")
    if rg:
        br = rg.get("breadth") or {}
        L += ["## Market regime", "",
              f"- **{rg.get('trend')} · {rg.get('volatility')} · "
              f"{rg.get('character')}** (as of {rg.get('as_of')})",
              f"- Breadth: {_pct(br.get('pct_above_200dma'))} above 200-day MA "
              f"({br.get('label', '—')})",
              f"- {rg.get('reason', '')}", ""]

    strategies = ts.get("strategies", {})
    if any(s.get("kind") == "equity" for s in strategies.values()):
        L += ["## Strategy performance (full history)", ""]
        L += _strategy_rows(strategies)
        L.append("")

    if risk:
        L += ["## Risk", "",
              f"- Status **{risk.get('status')}**"
              + (" · **EMERGENCY**" if risk.get("emergency") else "")
              + f" — {risk.get('reason', '')}"]
        L += [f"  - {name.replace('_', ' ')}: {_pct(c.get('value'), True)} "
              f"(limit {_pct(c.get('limit'), True)}) → {c.get('status')}"
              for name, c in (risk.get("checks") or {}).items()]
        L.append("")

    if factors and factors.get("factors"):
        L += ["## Top factor signals", ""]
        for k, v in factors["factors"].items():
            top = (v.get("top") or [{}])[0]
            if top.get("symbol"):
                L.append(f"- **{k.replace('_', ' ')}** → {top['symbol']} "
                         f"({_num(top.get('score'))})")
        L.append("")

    L += ["---",
          "_Research only. Every strategy is paper / pre-registered; nothing "
          "places a live order._"]
    return "\n".join(L)


def main():
    md = build_summary()
    out = RESULTS_DIR / "research_summary.md"
    RESULTS_DIR.mkdir(exist_ok=True)
    out.write_text(md)
    print(f"Wrote {out} ({len(md)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
